# Travis CI configuration for the Serial::Core Perl library.

language: perl

perl:
    - "5.8"
    - "5.10"
    - "5.12"
    - "5.14"
    - "5.16"
    - "5.18"
    - "5.20"

branches:
    only:
        - master
        - dev

script: prove -Isrc 
