## Travis CI configuration for the Serial::Core Perl library.
##
##  <https://travis-ci.org/mdklatt/serial-perl>
##
language: perl

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

branches:
  only:
    - master
    - dev

sudo: false

before_script:
  - perl Build.PL

script: 
  - ./Build test
