---
abstract: 'Read and write sequential record-oriented data.'
author:
  - 'Michael Klatt <mdklatt@ou.edu>'
build_requires: {}
configure_requires:
  Module::Build: '0.06'
  Pod::POM::View::Restructured: '0'
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Serial-Core
resources:
  license: http://dev.perl.org/licenses/
version: 0.002001_001
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
